apiVersion: v1
kind: Secret
metadata:
  name: {{ secret_resource_name }} 
  annotations:
    serving.kserve.io/s3-endpoint: {{ s3_endpoint_url }}
    serving.kserve.io/s3-usehttps: {{ s3_use_https }}
    serving.kserve.io/s3-useanoncredential: {{ s3_use_anon_credential }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ aws_secret_access_key }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ service_account_resource_name }}
  annotations:
    serving.kserve.io/s3-endpoint: {{ s3_endpoint_url }}
    serving.kserve.io/s3-usehttps: {{ s3_use_https }}
    serving.kserve.io/s3-useanoncredential: {{ s3_use_anon_credential }}
secrets:
  - name: {{ secret_resource_name }}